### ISSUE TITLE
[DEFECT] Plugin installation procedure

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#1109]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
Running ```./scripts/install_plugins.py --all``` more then once would just overvrite the config file
in the pluings directory

##### What did you see instead?
If you run ```./scripts/install_plugins.py --all``` more than once the following error appears:

```
[alfoa][~/projects/raven_github/raven]> ./scripts/install_plugins.py --all
Initializing plugin "CashFlow"
 ... initializing plugin submodule CashFlow ...
 ... plugin located at "/Users/alfoa/projects/raven_github/raven/plugins/CashFlow" ...
Initializing plugin "PRAplugin"
 ... initializing plugin submodule PRAplugin ...
 ... plugin located at "/Users/alfoa/projects/raven_github/raven/plugins/PRAplugin" ...
Initializing plugin "ExamplePlugin"
 ... initializing plugin submodule ExamplePlugin ...
 ... plugin located at "/Users/alfoa/projects/raven_github/raven/plugins/ExamplePlugin" ...
Installing plugins ...
Traceback (most recent call last):
  File "./scripts/install_plugins.py", line 131, in <module>
    match = pluginHandler.updatePluginXML(root, name, plugDir)
  File "/Users/alfoa/projects/raven_github/raven/scripts/plugin_handler.py", line 101, in updatePluginXML
    match = root.findall('./plugin/name[.=\'{}\']/..'.format(name))[0]
  File "/Users/alfoa/miniconda2/lib/python2.7/xml/etree/ElementTree.py", line 390, in findall
    return ElementPath.findall(self, path, namespaces)
  File "/Users/alfoa/miniconda2/lib/python2.7/xml/etree/ElementPath.py", line 293, in findall
    return list(iterfind(elem, path, namespaces))
  File "/Users/alfoa/miniconda2/lib/python2.7/xml/etree/ElementPath.py", line 263, in iterfind
    selector.append(ops[token[0]](next, token))
  File "/Users/alfoa/miniconda2/lib/python2.7/xml/etree/ElementPath.py", line 224, in prepare_predicate
    raise SyntaxError("invalid predicate")
SyntaxError: invalid predicate
```

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. execute ```./scripts/install_plugins.py --all```
2. execute ```./scripts/install_plugins.py --all```
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Any
 - Version: [e.g. 22] Any
 - Dependencies Installation: [CONDA or PIP] Any

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
I was not able to duplicate this; running it multiple times in succession worked as expected:

```bash
inl606705:(plugins/defects)~/projects/raven 2019-12-02 09:13:01
$./scripts/install_plugins.py --all
Initializing plugin "CashFlow"
 ... initializing plugin submodule CashFlow ...
 ... plugin located at "/Users/talbpw/projects/raven/plugins/CashFlow" ...
Initializing plugin "PRAplugin"
 ... initializing plugin submodule PRAplugin ...
 ... plugin located at "/Users/talbpw/projects/raven/plugins/PRAplugin" ...
Initializing plugin "ExamplePlugin"
 ... initializing plugin submodule ExamplePlugin ...
 ... plugin located at "/Users/talbpw/projects/raven/plugins/ExamplePlugin" ...
Installing plugins ...
Updating existing location of plugin "CashFlow" from "/Users/talbpw/projects/CashFlow" to "/Users/talbpw/projects/raven/plugins/CashFlow"
 ... plugin "CashFlow" path updated to "/Users/talbpw/projects/raven/plugins/CashFlow" ...
 ... plugin "CashFlow" informed of RAVEN at "/Users/talbpw/projects/raven/framework"...
 ... plugin "CashFlow" succesfully installed!
 ... plugin "PRAplugin" path updated to "/Users/talbpw/projects/raven/plugins/PRAplugin" ...
 ... plugin "PRAplugin" informed of RAVEN at "/Users/talbpw/projects/raven/framework"...
 ... plugin "PRAplugin" succesfully installed!
 ... plugin "ExamplePlugin" path updated to "/Users/talbpw/projects/raven/plugins/ExamplePlugin" ...
 ... plugin "ExamplePlugin" informed of RAVEN at "/Users/talbpw/projects/raven/framework"...
 ... plugin "ExamplePlugin" succesfully installed!
inl606705:(plugins/defects)~/projects/raven 2019-12-02 09:13:10
$./scripts/install_plugins.py --all
Initializing plugin "CashFlow"
 ... initializing plugin submodule CashFlow ...
 ... plugin located at "/Users/talbpw/projects/raven/plugins/CashFlow" ...
Initializing plugin "PRAplugin"
 ... initializing plugin submodule PRAplugin ...
 ... plugin located at "/Users/talbpw/projects/raven/plugins/PRAplugin" ...
Initializing plugin "ExamplePlugin"
 ... initializing plugin submodule ExamplePlugin ...
 ... plugin located at "/Users/talbpw/projects/raven/plugins/ExamplePlugin" ...
Installing plugins ...
 ... plugin "CashFlow" path updated to "/Users/talbpw/projects/raven/plugins/CashFlow" ...
 ... plugin "CashFlow" informed of RAVEN at "/Users/talbpw/projects/raven/framework"...
 ... plugin "CashFlow" succesfully installed!
 ... plugin "PRAplugin" path updated to "/Users/talbpw/projects/raven/plugins/PRAplugin" ...
 ... plugin "PRAplugin" informed of RAVEN at "/Users/talbpw/projects/raven/framework"...
 ... plugin "PRAplugin" succesfully installed!
 ... plugin "ExamplePlugin" path updated to "/Users/talbpw/projects/raven/plugins/ExamplePlugin" ...
 ... plugin "ExamplePlugin" informed of RAVEN at "/Users/talbpw/projects/raven/framework"...
 ... plugin "ExamplePlugin" succesfully installed!
inl606705:(plugins/defects)~/projects/raven 2019-12-02 09:13:12
$./scripts/install_plugins.py --all
Initializing plugin "CashFlow"
 ... initializing plugin submodule CashFlow ...
 ... plugin located at "/Users/talbpw/projects/raven/plugins/CashFlow" ...
Initializing plugin "PRAplugin"
 ... initializing plugin submodule PRAplugin ...
 ... plugin located at "/Users/talbpw/projects/raven/plugins/PRAplugin" ...
Initializing plugin "ExamplePlugin"
 ... initializing plugin submodule ExamplePlugin ...
 ... plugin located at "/Users/talbpw/projects/raven/plugins/ExamplePlugin" ...
Installing plugins ...
 ... plugin "CashFlow" path updated to "/Users/talbpw/projects/raven/plugins/CashFlow" ...
 ... plugin "CashFlow" informed of RAVEN at "/Users/talbpw/projects/raven/framework"...
 ... plugin "CashFlow" succesfully installed!
 ... plugin "PRAplugin" path updated to "/Users/talbpw/projects/raven/plugins/PRAplugin" ...
 ... plugin "PRAplugin" informed of RAVEN at "/Users/talbpw/projects/raven/framework"...
 ... plugin "PRAplugin" succesfully installed!
 ... plugin "ExamplePlugin" path updated to "/Users/talbpw/projects/raven/plugins/ExamplePlugin" ...
 ... plugin "ExamplePlugin" informed of RAVEN at "/Users/talbpw/projects/raven/framework"...
 ... plugin "ExamplePlugin" succesfully installed!
inl606705:(plugins/defects)~/projects/raven 2019-12-02 09:13:13
```

**Comment by PaulTalbot-INL** [comment]
I further tried the same with an underscore in the path and did not see an issue:
```
inl606705:(devel)~/projects/main_raven 2019-12-02 09:15:16
$./scripts/install_plugins.py -a
Initializing plugin "CashFlow"
 ... initializing plugin submodule CashFlow ...
 ... plugin located at "/Users/talbpw/projects/main_raven/plugins/CashFlow" ...
Initializing plugin "PRAplugin"
 ... initializing plugin submodule PRAplugin ...
 ... plugin located at "/Users/talbpw/projects/main_raven/plugins/PRAplugin" ...
Initializing plugin "ExamplePlugin"
 ... initializing plugin submodule ExamplePlugin ...
 ... plugin located at "/Users/talbpw/projects/main_raven/plugins/ExamplePlugin" ...
Installing plugins ...
 ... plugin "CashFlow" path created as "/Users/talbpw/projects/main_raven/plugins/CashFlow" ...
 ... plugin "CashFlow" informed of RAVEN at "/Users/talbpw/projects/main_raven/framework"...
 ... plugin "CashFlow" succesfully installed!
 ... plugin "PRAplugin" path created as "/Users/talbpw/projects/main_raven/plugins/PRAplugin" ...
 ... plugin "PRAplugin" informed of RAVEN at "/Users/talbpw/projects/main_raven/framework"...
 ... plugin "PRAplugin" succesfully installed!
 ... plugin "ExamplePlugin" path created as "/Users/talbpw/projects/main_raven/plugins/ExamplePlugin" ...
 ... plugin "ExamplePlugin" informed of RAVEN at "/Users/talbpw/projects/main_raven/framework"...
 ... plugin "ExamplePlugin" succesfully installed!
inl606705:(devel)~/projects/main_raven 2019-12-02 09:15:22
$./scripts/install_plugins.py -a
Initializing plugin "CashFlow"
 ... initializing plugin submodule CashFlow ...
 ... plugin located at "/Users/talbpw/projects/main_raven/plugins/CashFlow" ...
Initializing plugin "PRAplugin"
 ... initializing plugin submodule PRAplugin ...
 ... plugin located at "/Users/talbpw/projects/main_raven/plugins/PRAplugin" ...
Initializing plugin "ExamplePlugin"
 ... initializing plugin submodule ExamplePlugin ...
 ... plugin located at "/Users/talbpw/projects/main_raven/plugins/ExamplePlugin" ...
Installing plugins ...
 ... plugin "CashFlow" path updated to "/Users/talbpw/projects/main_raven/plugins/CashFlow" ...
 ... plugin "CashFlow" informed of RAVEN at "/Users/talbpw/projects/main_raven/framework"...
 ... plugin "CashFlow" succesfully installed!
 ... plugin "PRAplugin" path updated to "/Users/talbpw/projects/main_raven/plugins/PRAplugin" ...
 ... plugin "PRAplugin" informed of RAVEN at "/Users/talbpw/projects/main_raven/framework"...
 ... plugin "PRAplugin" succesfully installed!
 ... plugin "ExamplePlugin" path updated to "/Users/talbpw/projects/main_raven/plugins/ExamplePlugin" ...
 ... plugin "ExamplePlugin" informed of RAVEN at "/Users/talbpw/projects/main_raven/framework"...
 ... plugin "ExamplePlugin" succesfully installed!
```

**Comment by alfoa** [comment]
Closing... It looks like it is not a real issue.
