### ISSUE TITLE
[DEFECT] Title Here

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#1333]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
If the trajectory ```N``` is removed after the trajectory ```N-1``` is, a crash happens

##### What did you see instead?
a crash
```
( 9949.15 sec) GradientDescent          : DEBUG           -> Trajectory 1 has converged successfully 1 / 1 time(s)!
Traceback (most recent call last):
  File "/Users/alfoa/projects/raven_github/raven/framework/Driver.py", line 305, in <module>
    raven()
  File "/Users/alfoa/projects/raven_github/raven/framework/Driver.py", line 258, in raven
    simulation.run()
  File "/Users/alfoa/projects/raven_github/raven/framework/Simulation.py", line 750, in run
    stepInstance.takeAstep(stepInputDict)
  File "/Users/alfoa/projects/raven_github/raven/framework/Steps.py", line 338, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/Users/alfoa/projects/raven_github/raven/framework/Steps.py", line 693, in _localTakeAstepRun
    sampler.finalizeActualSampling(finishedJob,model,inputs)
  File "/Users/alfoa/projects/raven_github/raven/framework/Samplers/Sampler.py", line 1033, in finalizeActualSampling
    self.localFinalizeActualSampling(jobObject,model,myInput)
  File "/Users/alfoa/projects/raven_github/raven/framework/Optimizers/RavenSampled.py", line 265, in localFinalizeActualSampling
    self._useRealization(info, rlz)
  File "/Users/alfoa/projects/raven_github/raven/framework/Optimizers/GradientDescent.py", line 347, in _useRealization
    self._resolveNewOptPoint(traj, rlz, optVal, info)
  File "/Users/alfoa/projects/raven_github/raven/framework/Optimizers/RavenSampled.py", line 469, in _resolveNewOptPoint
    self._updatePersistence(traj, converged, optVal)
  File "/Users/alfoa/projects/raven_github/raven/framework/Optimizers/GradientDescent.py", line 672, in _updatePersistence
    self._closeTrajectory(traj, 'converge', 'converged', optVal)
  File "/Users/alfoa/projects/raven_github/raven/framework/Optimizers/RavenSampled.py", line 621, in _closeTrajectory
    Optimizer._closeTrajectory(self, traj, action, reason, value)
  File "/Users/alfoa/projects/raven_github/raven/framework/Optimizers/Optimizer.py", line 445, in _closeTrajectory
    self._activeTraj.remove(traj)
ValueError: list.remove(x): x not in list
```

##### Do you have a suggested fix for the development team?

 
**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
That's pretty bizarre! I don't think we use the location in the list to add, track, or remove the trajectories, so it's strange that we try to close a trajectory that isn't there.

**Comment by alfoa** [comment]
agree, I need to investigate further...I am trying to understand why it happens
