### ISSUE TITLE
[TASK] Empty variable groups

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#1344]
--------
Issue Description
--------

If a VariableGroup is empty, but has a space in it, such as
```xml
<Group name="empty"> </Group>
```
then RAVEN crashes with:
```
Traceback (most recent call last):
  File "/Users/talbpw/projects/raven/framework/Driver.py", line 305, in <module>
    raven()
  File "/Users/talbpw/projects/raven/framework/Driver.py", line 258, in raven
    simulation.run()
  File "/Users/talbpw/projects/raven/framework/Simulation.py", line 750, in run
    stepInstance.takeAstep(stepInputDict)
  File "/Users/talbpw/projects/raven/framework/Steps.py", line 342, in takeAstep
    self._initializeStep(inDictionary)
  File "/Users/talbpw/projects/raven/framework/Steps.py", line 272, in _initializeStep
    self._localInitializeStep(inDictionary)
  File "/Users/talbpw/projects/raven/framework/Steps.py", line 612, in _localInitializeStep
    SingleRun._localInitializeStep(self,inDictionary)
  File "/Users/talbpw/projects/raven/framework/Steps.py", line 466, in _localInitializeStep
    inDictionary['Model'].initialize(inDictionary['jobHandler'].runInfoDict,inDictionary['Input'],modelInitDict)
  File "/Users/talbpw/projects/raven/framework/Models/Code.py", line 334, in initialize
    self.code.initialize(copy.deepcopy(runInfoDict), self.oriInputFiles)
  File "/Users/talbpw/projects/raven/framework/CodeInterfaces/RAVEN/RAVENInterface.py", line 180, in initialize
    parser = RAVENparser.RAVENparser(oriInputFiles[index].getAbsFile())
  File "/Users/talbpw/projects/raven/framework/CodeInterfaces/RAVEN/RAVENparser.py", line 65, in __init__
    self.varGroups = mathUtils.readVariableGroups(variableGroupNode,messageHandler,messageUser)
  File "/Users/talbpw/projects/raven/framework/utils/mathUtils.py", line 893, in readVariableGroups
    varGroup.readXML(nodes[name], messageHandler, varGroups)
  File "/Users/talbpw/projects/raven/framework/VariableGroups.py", line 67, in readXML
    if dep[0] in '+-^%':
IndexError: string index out of range
```
While an empty variable group seems abnormal, it also isn't something we should crash on. At the bare minimum we could provide useful information; at best we could simply propagate the empty variable group.

This occurs most often when the RAVEN input file is generated automatically.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@Jimmy-INL  the closure checklist process has not been performed

**Comment by Jimmy-INL** [comment]
Which one?
