### ISSUE TITLE
[DEFECT] statsmodels error

### ISSUE THREAD

**Issue by JiaZhou-PU** [idaholab/raven#1378]
--------
Defect Description
--------

**Describe the defect**
When using the internal parallel as True,  and sampling the ARMA, it might cause the error of `statsmodels.tsa.statespace._initialization.dInitialization.__init__`
##### What did you see instead?
```
(   33.51 sec) STEP MULTIRUN            : Message         -> ***       Beginning run       ***
(pid=57717) Unable to load "timingProfile" decorator; replacing with passthrough ...
(pid=57717) Unable to load "memoryProfile" decorator; replacing with passthrough ...
(pid=57718) Unable to load "timingProfile" decorator; replacing with passthrough ...
(pid=57718) Unable to load "memoryProfile" decorator; replacing with passthrough ...
(pid=57717) INPUT SPEC ERROR adding checked and unchecked to lowerBound  in  UniformDiscrete len 1
(pid=57717) INPUT SPEC ERROR adding checked and unchecked to upperBound  in  UniformDiscrete len 1
(pid=57717) INPUT SPEC ERROR adding checked and unchecked to lowerBound  in  LogUniform len 1
(pid=57717) INPUT SPEC ERROR adding checked and unchecked to upperBound  in  LogUniform len 1
(pid=57718) INPUT SPEC ERROR adding checked and unchecked to lowerBound  in  UniformDiscrete len 1
(pid=57718) INPUT SPEC ERROR adding checked and unchecked to upperBound  in  UniformDiscrete len 1
(pid=57718) INPUT SPEC ERROR adding checked and unchecked to lowerBound  in  LogUniform len 1
(pid=57718) INPUT SPEC ERROR adding checked and unchecked to upperBound  in  LogUniform len 1
(pid=57718) /home/zhoujia/.conda/envs/raven_libraries/lib/python3.7/site-packages/patsy/constraint.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
(pid=57718)   from collections import Mapping
(pid=57717) /home/zhoujia/.conda/envs/raven_libraries/lib/python3.7/site-packages/patsy/constraint.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
(pid=57717)   from collections import Mapping
Traceback (most recent call last):
  File "/home/zhoujia/projects/raven/framework/Driver.py", line 305, in <module>
    raven()
  File "/home/zhoujia/projects/raven/framework/Driver.py", line 258, in raven
    simulation.run()
  File "/home/zhoujia/projects/raven/framework/Simulation.py", line 762, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/zhoujia/projects/raven/framework/Steps.py", line 346, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/home/zhoujia/projects/raven/framework/Steps.py", line 690, in _localTakeAstepRun
    myLambda([finishedJob,outputs[outIndex]])
  File "/home/zhoujia/projects/raven/framework/Steps.py", line 637, in <lambda>
    self._outputCollectionLambda.append( (lambda x: inDictionary['Model'].collectOutput(x[0],x[1]), outIndex) )
  File "/home/zhoujia/projects/raven/framework/Models/EnsembleModel.py", line 453, in collectOutput
    evaluation = finishedJob.getEvaluation()
  File "/home/zhoujia/projects/raven/framework/Runners/InternalRunner.py", line 124, in getEvaluation
    self._collectRunnerResponse()
  File "/home/zhoujia/projects/raven/framework/Runners/DistributedMemoryRunner.py", line 109, in _collectRunnerResponse
    self.runReturn = ray.get(self.thread) if im.isLibAvail("ray") else self.thread()
  File "/home/zhoujia/.conda/envs/raven_libraries/lib/python3.7/site-packages/ray/worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::evaluateSample() (pid=57718, ip=141.221.84.10)
  File "python/ray/_raylet.pyx", line 448, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 465, in ray._raylet.execute_task
  File "/home/zhoujia/.conda/envs/raven_libraries/lib/python3.7/site-packages/ray/serialization.py", line 308, in deserialize_objects
    self._deserialize_object(data, metadata, object_ref))
  File "/home/zhoujia/.conda/envs/raven_libraries/lib/python3.7/site-packages/ray/serialization.py", line 247, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata)
  File "/home/zhoujia/.conda/envs/raven_libraries/lib/python3.7/site-packages/ray/serialization.py", line 226, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/zhoujia/.conda/envs/raven_libraries/lib/python3.7/site-packages/ray/serialization.py", line 214, in _deserialize_pickle5_data
    obj = pickle.loads(in_band, buffers=buffers)
  File "statsmodels/tsa/statespace/_initialization.pyx", line 227, in statsmodels.tsa.statespace._initialization.dInitialization.__init__
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@joshua-cogliati-inl  here we need your expertise... there are threads about this pandas etc.

**Comment by JiaZhou-PU** [comment]
Can't repeat error

**Comment by alfoa** [comment]
@joshua-cogliati-inl  looks like that it is not "reproducible"
