### ISSUE TITLE
outdated input files in the user_guide/ravenInputs

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#145]
--------
Issue Description
--------
##### What did you expect to see happen?

I should see no errors when run the input files under folder user_guide/ravenInputs

##### What did you see instead?
I got the following error:
Traceback (most recent call last):
  File "/Users/wangc/projects/wangc/raven/framework/Driver.py", line 215, in <module>
    simulation.XMLread(root,runInfoSkip=set(["DefaultInputFile"]),xmlFilename=inputFile)
  File "/Users/wangc/projects/wangc/raven/framework/Simulation.py", line 747, in XMLread
    self.whichDict[Class][subType][name].readXML(childChild, self.messageHandler, globalAttributes=globalAttributes)
  File "/Users/wangc/projects/wangc/raven/framework/BaseClasses.py", line 105, in readXML
    self._readMoreXML(xmlNode)
  File "/Users/wangc/projects/wangc/raven/framework/OutStreams/OutStreamManager.py", line 85, in _readMoreXML
    self.localReadXML(xmlNode)
  File "/Users/wangc/projects/wangc/raven/framework/OutStreams/OutStreamPlot.py", line 868, in localReadXML
    self.raiseAnError(IOError,"the 'dim' attribute has been deprecated. This warning became an error in January 2017")
  File "/Users/wangc/projects/wangc/raven/framework/MessageHandler.py", line 101, in raiseAnError
    self.messageHandler.error(self,etype,msg,str(tag),verbosity,color)
  File "/Users/wangc/projects/wangc/raven/framework/MessageHandler.py", line 314, in error
    raise etype(message)
IOError: the 'dim' attribute has been deprecated. This warning became an error in January 2017

##### Do you have a suggested fix for the development team?
Remove 'dim' attribute

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement? __Improvement__
- [x] 2. Is it tagged with a priority: critical, normal or minor? __normal__
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? __N/A__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __Not a defect__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) __duplicate files__

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? 
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) 
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? 
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Thanks @alfoa, these tests already exist in the test/framework, and the folder user_guide/ravenInput should be removed.

**Comment by wangcj05** [comment]
This issue should be closed by pull request #146. Since pull request #146 has been merged, this issue can be closed now.
