### ISSUE TITLE
[DEFECT] Title Here

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#1521]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
The plugin check in RavenRunningRaven randomly fail with the following crash 

##### What did you see instead?
``CONDA
raven_libraries       *  /Users/alfoa/miniconda3/envs/raven_libraries
Installing ExamplePlugin...
Initializing plugin "/Users/alfoa/projects/raven_github/raven/scripts/../plugins/ExamplePlugin"
 ... plugin located at "/Users/alfoa/projects/raven_github/raven/plugins/ExamplePlugin" ...
Installing plugins ...
 ... plugin "ExamplePlugin" path updated to "/Users/alfoa/projects/raven_github/raven/plugins/ExamplePlugin" ...
Traceback (most recent call last):
  File "/Users/alfoa/projects/raven_github/raven/scripts/install_plugins.py", line 146, in <module>
    rLoc = pluginHandler.tellPluginAboutRaven(plugDir)
  File "/Users/alfoa/projects/raven_github/raven/scripts/plugin_handler.py", line 121, in tellPluginAboutRaven
    root, _ = xmlUtils.loadToTree(configFile)
  File "/Users/alfoa/projects/raven_github/raven/scripts/../framework/utils/xmlUtils.py", line 250, in loadToTree
    tree = ET.parse(filename, parser=parser)
  File "/Users/alfoa/miniconda3/envs/raven_libraries/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/Users/alfoa/miniconda3/envs/raven_libraries/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

##### Do you have a suggested fix for the development team?


**Describe how to Reproduce**
Steps to reproduce the behavior:
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: [e.g. iOS]
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
I found the reason.

tellPluginAboutRaven()  is not "thread-safe". Since we always re-write the config file in the plugins, it might happen that tere is a processor that is writing and another that is reading at the same time and the "reading" one fails

**Comment by PaulTalbot-INL** [comment]
Ohhh, interesting. What a pain.

**Comment by alfoa** [comment]
Fixed in PR  #1494
