### ISSUE TITLE
[DEFECT] import (discovery) of RAVEN ``contrib`` seems to be compromised

### ISSUE THREAD

**Issue by aalfonsi** [idaholab/raven#1793]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

I did a fresh installation of RAVEN and the execution of tests cases result in an ```import``` error:
```
 ... successfully imported "ExamplePlugin" ...
Traceback (most recent call last):
  File "/Users/alfoa/projects/raven/framework/Driver.py", line 31, in <module>
    from Simulation import Simulation
  File "/Users/alfoa/projects/raven/framework/Simulation.py", line 28, in <module>
    import Steps
  File "/Users/alfoa/projects/raven/framework/Steps/__init__.py", line 22, in <module>
    from .Factory import factory
  File "/Users/alfoa/projects/raven/framework/Steps/Factory.py", line 24, in <module>
    from .SingleRun import SingleRun
  File "/Users/alfoa/projects/raven/framework/Steps/SingleRun.py", line 30, in <module>
    import Models
  File "/Users/alfoa/projects/raven/framework/Models/__init__.py", line 25, in <module>
    from .Dummy import Dummy
  File "/Users/alfoa/projects/raven/framework/Models/Dummy.py", line 31, in <module>
    from Decorators.Parallelization import Parallel
  File "/Users/alfoa/projects/raven/framework/Decorators/Parallelization.py", line 20, in <module>
    from utils import importerUtils as im
  File "/Users/alfoa/projects/raven/framework/utils/importerUtils.py", line 26, in <module>
    import contrib.lazy.lazy_loader as lazy_loader
ModuleNotFoundError: No module named 'contrib.lazy'
```

This issue seems to be triggered by the modifications added in https://github.com/idaholab/raven/pull/1685 (even if it does not seem clear why to me)

### Steps to Reproduce

Fresh installation of RAVEN.

### Expected Behavior

Correctly import RAVEN dependencies in ```contrib```

### Screenshots and Input Files

```
 ... successfully imported "ExamplePlugin" ...
Traceback (most recent call last):
  File "/Users/alfoa/projects/raven/framework/Driver.py", line 31, in <module>
    from Simulation import Simulation
  File "/Users/alfoa/projects/raven/framework/Simulation.py", line 28, in <module>
    import Steps
  File "/Users/alfoa/projects/raven/framework/Steps/__init__.py", line 22, in <module>
    from .Factory import factory
  File "/Users/alfoa/projects/raven/framework/Steps/Factory.py", line 24, in <module>
    from .SingleRun import SingleRun
  File "/Users/alfoa/projects/raven/framework/Steps/SingleRun.py", line 30, in <module>
    import Models
  File "/Users/alfoa/projects/raven/framework/Models/__init__.py", line 25, in <module>
    from .Dummy import Dummy
  File "/Users/alfoa/projects/raven/framework/Models/Dummy.py", line 31, in <module>
    from Decorators.Parallelization import Parallel
  File "/Users/alfoa/projects/raven/framework/Decorators/Parallelization.py", line 20, in <module>
    from utils import importerUtils as im
  File "/Users/alfoa/projects/raven/framework/utils/importerUtils.py", line 26, in <module>
    import contrib.lazy.lazy_loader as lazy_loader
ModuleNotFoundError: No module named 'contrib.lazy'
```

### OS

MacOS

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [ ] If the issue is a defect, is the defect fixed?
- [ ] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@PaulTalbot-INL FYI.

**Comment by PaulTalbot-INL** [comment]
Hm. It's odd that none of our regressions machines with fresh checkouts are seeing this issue. Is this local to a specialized install?

**Comment by joshua-cogliati-inl** [comment]
Hm, is the line in setupCpp() in CustomDriver/DriverUtils.py:
utils.add_path(os.path.join(frameworkDir,'contrib'))
not getting run before the import for Simulation?

**Comment by joshua-cogliati-inl** [comment]
Also, https://github.com/idaholab/raven/pull/1784 will likely either fix this, or really mess it up.

**Comment by aalfonsi** [comment]
it seems that ```utils.add_path(os.path.join(frameworkDir,'contrib'))``` is run (I checked before opening the issue) but without the "__init__" the hierarchy is not correctly captured. Another approach is to modify ```utils.add_path(os.path.join(frameworkDir,'contrib'))``` to ```utils.add_path_recursive(os.path.join(frameworkDir,'contrib'))``` that worked too.

I do not know why this has been triggered by the  https://github.com/idaholab/raven/pull/1685 (and not before, since the calls have been simply moved and not "modified")...

**Comment by joshua-cogliati-inl** [comment]
Hm, https://github.com/idaholab/raven/pull/1773 also changes how raven does paths and went in soon after #1685

**Comment by aalfonsi** [comment]
New approach works without a need for a fix. Thank you.
