### ISSUE TITLE
[TASK] raven libraries with ABCE enveriment.

### ISSUE THREAD

**Issue by JiaZhou-PU** [idaholab/raven#2130]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
Using RAVEN to run ABCE, there are some dependency problems. RAVEN would return:

```
               __________________________________________________
              /_________________________________________________ |
             //                                                 ||
            //    ____ ________        _______    __________    ||
           //    // || ||     \\      //     \\   ||       |    ||
          //    //  || ||      \\    //       /   ||            ||
         //    //   || ||      //   ||            ||            ||
        //    //    || ||_____//    ||            ||            ||
       //    //     || ||      \\   ||            ||            ||
      //    //      || ||       \\  ||            ||            ||
     //    //       || ||        || ||          \ ||            ||
    //    //________||_||        //  \\        // ||____        ||
   //    //         || ||       //    \\      //  ||            ||
  ||    //_         ||_||______//      \\____//  _||________|   ||
  ||                                                            ||
  ||____________________________________________________________||
  |______________________________________________________________|

   Agent           Based            Capacity            Expansion

  _______________________________________________________________

INFO: Creating a new database file at /Users/l00317783/Library/CloudStorage/Box-Box/abceheron/rra/abcesetting/sample/1/outputs/ABCE_ERCOT_PWRC2N/abce_db.db.
INFO: Database created in file '/Users/l00317783/Library/CloudStorage/Box-Box/abceheron/rra/abcesetting/sample/1/outputs/ABCE_ERCOT_PWRC2N/abce_db.db'.
WARNING: No sysimage file found at /Users/l00317783/Library/CloudStorage/Box-Box/abce/env/abceSysimage.so. Execution will proceed, but Julia may run extremely slowly. If you already have a sysimage file, please move it to the filename /Users/l00317783/Library/CloudStorage/Box-Box/abce/env/abceSysimage.so. If you do not have a sysimage file, please run 'julia make_sysimage.jl --mode=abce' in this directory.
============================================================
   Simulation step: 0
============================================================
DEBUG: Running the scenario reduction algorithm...
INFO: Scenario reduction complete.
Agent #201 is taking its turn...
ERROR: LoadError: InitError: Artifact "OpenSpecFun" was not installed correctly. Try `using Pkg; Pkg.instantiate()` to re-install all missing resources.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] _artifact_str(__module__::Module, artifacts_toml::String, name::SubString{String}, path_tail::String, artifact_dict::Dict{String, Any}, hash::Base.SHA1, platform::Base.BinaryPlatforms.Platform, lazyartifacts::Any)
    @ Artifacts /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Artifacts/src/Artifacts.jl:552
  [3] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./essentials.jl:729
  [4] invokelatest(::Any, ::Any, ::Vararg{Any})
    @ Base ./essentials.jl:726
  [5] macro expansion
    @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Artifacts/src/Artifacts.jl:681 [inlined]
  [6] find_artifact_dir()
    @ OpenSpecFun_jll ~/project/miniconda3/envs/raven_libraries/share/julia/packages/JLLWrappers/QpMQW/src/wrapper_generators.jl:17
  [7] __init__()
    @ OpenSpecFun_jll ~/project/miniconda3/envs/raven_libraries/share/julia/packages/OpenSpecFun_jll/1Zaof/src/wrappers/x86_64-apple-darwin-libgfortran4.jl:8
  [8] _include_from_serialized(pkg::Base.PkgId, path::String, depmods::Vector{Any})
    @ Base ./loading.jl:831
  [9] _tryrequire_from_serialized(pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:978
 [10] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1347
 [11] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
 [12] macro expansion
    @ ./loading.jl:1180 [inlined]
 [13] macro expansion
    @ ./lock.jl:223 [inlined]
 [14] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
 [15] include
    @ ./Base.jl:419 [inlined]
 [16] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1554
 [17] top-level scope
    @ stdin:1
during initialization of module OpenSpecFun_jll
in expression starting at /Users/l00317783/project/miniconda3/envs/raven_libraries/share/julia/packages/SpecialFunctions/gXPNz/src/SpecialFunctions.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile SpecialFunctions [276daf66-3868-5448-9aa4-cd146d93841b] to /Users/l00317783/project/miniconda3/envs/raven_libraries/share/julia/compiled/v1.8/SpecialFunctions/jl_HtCtoF.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1707
  [3] compilecache
    @ ./loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] include
    @ ./Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at /Users/l00317783/project/miniconda3/envs/raven_libraries/share/julia/packages/ForwardDiff/vXysl/src/ForwardDiff.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile ForwardDiff [f6369f11-7733-5829-9624-2563aa707210] to /Users/l00317783/project/miniconda3/envs/raven_libraries/share/julia/compiled/v1.8/ForwardDiff/jl_PrLI8q.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1707
  [3] compilecache
    @ ./loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] include(mod::Module, _path::String)
    @ Base ./Base.jl:419
 [10] include(x::String)
    @ MathOptInterface ~/project/miniconda3/envs/raven_libraries/share/julia/packages/MathOptInterface/wrorD/src/MathOptInterface.jl:7
 [11] top-level scope
    @ ~/project/miniconda3/envs/raven_libraries/share/julia/packages/MathOptInterface/wrorD/src/MathOptInterface.jl:253
 [12] include
    @ ./Base.jl:419 [inlined]
 [13] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1554
 [14] top-level scope
    @ stdin:1
in expression starting at /Users/l00317783/project/miniconda3/envs/raven_libraries/share/julia/packages/MathOptInterface/wrorD/src/Nonlinear/Nonlinear.jl:7
in expression starting at /Users/l00317783/project/miniconda3/envs/raven_libraries/share/julia/packages/MathOptInterface/wrorD/src/MathOptInterface.jl:7
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile MathOptInterface [b8f27783-ece8-5eb3-8dc8-9495eed66fee] to /Users/l00317783/project/miniconda3/envs/raven_libraries/share/julia/compiled/v1.8/MathOptInterface/jl_aava4P.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:1707
  [3] compilecache
    @ ./loading.jl:1651 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1337
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [6] macro expansion
    @ ./loading.jl:1180 [inlined]
  [7] macro expansion
    @ ./lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
  [9] include
    @ ./Base.jl:419 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1554
 [11] top-level scope
    @ stdin:1
in expression starting at /Users/l00317783/project/miniconda3/envs/raven_libraries/share/julia/packages/JuMP/ptoff/src/JuMP.jl:11
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile JuMP [4076af6c-e467-56ae-b986-b466b2749572] to /Users/l00317783/project/miniconda3/envs/raven_libraries/share/julia/compiled/v1.8/JuMP/jl_XkgbWa.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:1707
 [3] compilecache
   @ ./loading.jl:1651 [inlined]
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1337
 [5] _require_prelocked(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1200
 [6] macro expansion
   @ ./loading.jl:1180 [inlined]
 [7] macro expansion
   @ ./lock.jl:223 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1144
in expression starting at /Users/l00317783/Library/CloudStorage/Box-Box/abce/src/agent_choice.jl:19
Traceback (most recent call last):
  File "/Users/l00317783/Library/CloudStorage/Box-Box/abce/run.py", line 235, in <module>
    run_model()
  File "/Users/l00317783/Library/CloudStorage/Box-Box/abce/run.py", line 192, in run_model
    abce_model.step(demo=args.demo)
  File "/Users/l00317783/Library/CloudStorage/Box-Box/abce/src/model.py", line 380, in step
    self.schedule.step()
  File "/Users/l00317783/project/miniconda3/envs/raven_libraries/lib/python3.10/site-packages/mesa/time.py", line 125, in step
    agent.step()
  File "/Users/l00317783/Library/CloudStorage/Box-Box/abce/src/agent.py", line 161, in step
    sp = subprocess.check_call(julia_cmd, shell=True)
  File "/Users/l00317783/project/miniconda3/envs/raven_libraries/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'julia --project=/Users/l00317783/Library/CloudStorage/Box-Box/abce/env  /Users/l00317783/Library/CloudStorage/Box-Box/abce/src/agent_choice.jl --current_pd=0 --agent_id=201 --verbosity=3 --settings_file=settings.yml --inputs_path=inp3 --abce_abs_path=/Users/l00317783/Library/CloudStorage/Box-Box/abce' returned non-zero exit status 1.
```

ABCE running standalone would return:

```


               __________________________________________________
              /_________________________________________________ |
             //                                                 ||
            //    ____ ________        _______    __________    ||
           //    // || ||     \\      //     \\   ||       |    ||
          //    //  || ||      \\    //       /   ||            ||
         //    //   || ||      //   ||            ||            ||
        //    //    || ||_____//    ||            ||            ||
       //    //     || ||      \\   ||            ||            ||
      //    //      || ||       \\  ||            ||            ||
     //    //       || ||        || ||          \ ||            ||
    //    //________||_||        //  \\        // ||____        ||
   //    //         || ||       //    \\      //  ||            ||
  ||    //_         ||_||______//      \\____//  _||________|   ||
  ||                                                            ||
  ||____________________________________________________________||
  |______________________________________________________________|

   Agent           Based            Capacity            Expansion

  _______________________________________________________________

DEBUG: Deleting file /Users/l00317783/Library/CloudStorage/Box-Box/abceheron/rra/abcesetting/sample/1/outputs/ABCE_ERCOT_PWRC2N/abce_db.db from the output directory
INFO: Creating a new database file at /Users/l00317783/Library/CloudStorage/Box-Box/abceheron/rra/abcesetting/sample/1/outputs/ABCE_ERCOT_PWRC2N/abce_db.db.
INFO: Database created in file '/Users/l00317783/Library/CloudStorage/Box-Box/abceheron/rra/abcesetting/sample/1/outputs/ABCE_ERCOT_PWRC2N/abce_db.db'.
WARNING: No sysimage file found at /Users/l00317783/Library/CloudStorage/Box-Box/abce/env/abceSysimage.so. Execution will proceed, but Julia may run extremely slowly. If you already have a sysimage file, please move it to the filename /Users/l00317783/Library/CloudStorage/Box-Box/abce/env/abceSysimage.so. If you do not have a sysimage file, please run 'julia make_sysimage.jl --mode=abce' in this directory.
============================================================
   Simulation step: 0
============================================================
DEBUG: Running the scenario reduction algorithm...
INFO: Scenario reduction complete.
Agent #201 is taking its turn...
Agent #201's turn is complete.


All agent turns are complete.

DEBUG: Updates to assets:
DEBUG:    asset_id  agent_id unit_type  ...  total_capex  cap_pmt  C2N_reserved
0      2810       201      ngcc  ...          0.0      0.0             0
1      2811       201      ngcc  ...          0.0      0.0             0
2      2812       201      ngcc  ...          0.0      0.0             0
3      2813       201      ngct  ...          0.0      0.0             0
4      2814       201      ngct  ...          0.0      0.0             0
5      2815       201      ngct  ...          0.0      0.0             0

[6 rows x 10 columns]
DEBUG: 
Construction project updates (last 10 entries):
DEBUG:    asset_id  agent_id  period  ...  rtec  cum_construction_exp          anpe
0      2810       201     0.0  ...   3.0                   0.0  6.720000e+07
1      2811       201     0.0  ...   3.0                   0.0  6.720000e+07
2      2812       201     0.0  ...   3.0                   0.0  6.720000e+07
3      2813       201     0.0  ...   3.0                   0.0  1.541667e+07
4      2814       201     0.0  ...   3.0                   0.0  1.541667e+07
5      2815       201     0.0  ...   3.0                   0.0  1.541667e+07

[6 rows x 9 columns]
INFO: Postprocessing results...
DEBUG: Procesing data for agent 201's portfolio...
DEBUG: Loaded backend %s version %s.
DEBUG: findfont: Matching %s.
DEBUG: findfont: Matching %s to %s (%r) with score of %f.
INFO: Postprocessing complete.
```

**Describe the solution you'd like**
Here is the list of ABCE dependency:

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - mesa
  - openpyxl
  - pytest
  - matplotlib
  - yaml
  - julia=1.8
  
And Julia requirement:
"ArgParse"
"CPLEX"
"CSV"
"Conda"
"DataFrames"
"FileIO"
"GLPK"
"HDF5"
"Infiltrator"
"Ipopt"
"JLD2"
"JSON"
"JuMP"
"LinearAlgebra"
"Logging"
"MathOptInterface"
"Memento"
"PackageCompiler"
"PowerModels"
"PyCall"
"Requires"
"SQLite"
"Tables"
"XLSX"
"YAML"
"Cbc"
"HiGHS"

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by JiaZhou-PU** [comment]
@joshua-cogliati-inl Hi Josh, I have some issue using RAVEN to run ABCE because of the Julia requirments, I was wonder if RAVEN can add another Julia package to run it.

**Comment by joshua-cogliati-inl** [comment]
Hm, what would the manual command to do this look like (what conda or pip command or commands would I use to do this manually)?

**Comment by joshua-cogliati-inl** [comment]
Ah, it is in conda forge:
```
$ conda search -c conda-forge julia
Loading channels: done
# Name                       Version           Build  Channel             
julia                          0.5.2 blas_openblas_0  conda-forge         
julia                          0.5.2 blas_openblas_1  conda-forge         
julia                          0.5.2 blas_openblas_2  conda-forge         
julia                          0.5.2 blas_openblas_200  conda-forge         
julia                          0.5.2 blas_openblas_3  conda-forge         
julia                          0.5.2 blas_openblas_4  conda-forge         
julia                          0.5.2 blas_openblas_5  conda-forge         
julia                          0.5.2 blas_openblas_6  conda-forge         
julia                          0.6.0 blas_openblas_200  conda-forge         
julia                          0.6.1 blas_openblas_200  conda-forge         
julia                          0.6.1 blas_openblas_201  conda-forge         
julia                          0.6.1 blas_openblas_202  conda-forge         
julia                          0.6.1 blas_openblashfe40789_203  conda-forge         
julia                          1.0.0 blas_openblashfe40789_0  conda-forge         
julia                          1.0.1 blas_openblashfe40789_0  conda-forge         
julia                          1.0.2 blas_openblashfe40789_0  conda-forge         
julia                          1.0.3 blas_openblash12d65f3_2  conda-forge         
julia                          1.0.3 blas_openblash977ebb0_0  conda-forge         
julia                          1.0.3 blas_openblash977ebb0_1  conda-forge         
julia                          1.0.3      h1c3500e_3  conda-forge         
julia                          1.1.1      h14ade15_2  conda-forge         
julia                          1.1.1      h1c3500e_0  conda-forge         
julia                          1.1.1      h1c3500e_1  conda-forge         
julia                          1.1.1      h344ffa1_6  conda-forge         
julia                          1.1.1      h880f756_5  conda-forge         
julia                          1.1.1      hb80d53e_3  conda-forge         
julia                          1.1.1      hb80d53e_4  conda-forge         
julia                          1.1.1      hb80d53e_5  conda-forge         
julia                          1.1.1      hea32d20_7  conda-forge         
julia                          1.6.1      h96f571d_0  conda-forge         
julia                          1.6.2      h438a1c7_3  conda-forge         
julia                          1.6.2      h96f571d_0  conda-forge         
julia                          1.6.2      hbb0e23a_1  conda-forge         
julia                          1.6.3      h2a39549_1  conda-forge         
julia                          1.6.3      h438a1c7_0  conda-forge         
julia                          1.6.4      h2a39549_0  conda-forge         
julia                          1.6.4      h34dcedf_1  conda-forge         
julia                          1.6.4      h34dcedf_2  conda-forge         
julia                          1.6.4      h989b2f6_2  conda-forge         
julia                          1.6.5      h989b2f6_0  conda-forge         
julia                          1.6.5      h989b2f6_1  conda-forge         
julia                          1.6.5      h989b2f6_2  conda-forge         
julia                          1.7.0      h989b2f6_0  conda-forge         
julia                          1.7.1      h620718c_0  conda-forge         
julia                          1.7.1      h989b2f6_0  conda-forge         
julia                          1.7.1      h989b2f6_1  conda-forge         
julia                          1.7.1      h989b2f6_2  conda-forge         
julia                          1.7.1      h989b2f6_3  conda-forge         
julia                          1.7.2      h35b96e5_1  conda-forge         
julia                          1.7.2      h52e3dff_1  conda-forge         
julia                          1.7.2      h989b2f6_0  conda-forge         
julia                          1.7.3      h35b96e5_0  conda-forge         
julia                          1.7.3      h6f5dd7c_1  conda-forge         
julia                          1.8.0      h6f5dd7c_0  conda-forge         
julia                          1.8.0      h6f5dd7c_1  conda-forge         
julia                          1.8.0      h6f5dd7c_2  conda-forge         
julia                          1.8.0      h6f5dd7c_3  conda-forge         
julia                          1.8.1      h6f5dd7c_0  conda-forge         
julia                          1.8.2      h00c5a2e_1  conda-forge         
julia                          1.8.2      h6f5dd7c_0  conda-forge         
julia                          1.8.3      h00c5a2e_0  conda-forge         
julia                          1.8.4      h783901f_0  conda-forge         
julia                          1.8.5      h783901f_0  conda-forge         
julia                          1.9.0      hfacc78c_0  conda-forge         
julia                          1.9.1      hb81c242_0  conda-forge  
```

**Comment by biegelk** [comment]
Hmm. It looks like Julia is being included in the environment correctly, otherwise execution wouldn't even get to the point of trying to load packages; it would just crash with a `julia: command not found` error.

It gets as far as trying to load `JuMP`, which is the second package in the list at the top of the main Julia script. The first one, `Logging`, is a default library that comes pre-loaded with the base Julia installation. So clearly the environment isn't being recognized (yet again...).

I suspect this is our recurring issue with Julia environment management being terrible and un-portable. I have a meeting now, but I'll look into this today

**Comment by JiaZhou-PU** [comment]
> @JiaZhou-PU In your example above, ABCE works fine when run standalone. Is that being run in the RAVEN conda environment?

No it's in abce_env, when run in raven_libraries, it shows the Julia problem after(conda install mesa openpyxl, yaml and Julia)

**Comment by biegelk** [comment]
Okay, this might be something that can be temporarily fixed by the Julia environment workaround we used before. If you have Manifest.toml and Project.toml in your `abce/env/` directory, try the following:

1. Activate the `raven_libraries` conda environment
2. `cd` into the directory you're using to run ABCE through RAVEN
3. Run `julia`
4. Hit the `]` key to enter package management mode
5. Run `activate ~/path/to/abce/env/`
6. Run `status`
7. run `instantiate`
8. Backspace and then `exit()` to quit

Can you let me know what output that gives you?

**Comment by wangcj05** [comment]
can this be closed?
