### ISSUE TITLE
Tests fail with newer libraries 

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#224]
--------
Issue Description
--------
##### What did you expect to see happen?
The tests to pass

##### What did you see instead?
Several of the tests failed with things like:

```
framework.testFactorials:   File "/home/jjc/sub/raven/framework/Driver.py", line 278, in <module>
framework.testFactorials:     raven()
framework.testFactorials:   File "/home/jjc/sub/raven/framework/Driver.py", line 231, in raven
framework.testFactorials:     simulation.run()
framework.testFactorials:   File "/home/jjc/sub/raven/framework/Simulation.py", line 1051, in run
framework.testFactorials:     stepInstance.takeAstep(stepInputDict)
framework.testFactorials:   File "/home/jjc/sub/raven/framework/Steps.py", line 235, in takeAstep
framework.testFactorials:     self._initializeStep(inDictionary)
framework.testFactorials:   File "/home/jjc/sub/raven/framework/Steps.py", line 191, in _initializeStep
framework.testFactorials:     self._localInitializeStep(inDictionary)
framework.testFactorials:   File "/home/jjc/sub/raven/framework/Steps.py", line 465, in _localInitializeStep
framework.testFactorials:     self._initializeSampler(inDictionary)
framework.testFactorials:   File "/home/jjc/sub/raven/framework/Steps.py", line 448, in _initializeSampler
framework.testFactorials:     inDictionary[self.samplerType].initialize(**self._samplerInitDict)
framework.testFactorials:   File "/home/jjc/sub/raven/framework/Samplers/Sampler.py", line 503, in initialize
framework.testFactorials:     self.localInitialize()
framework.testFactorials:   File "/home/jjc/sub/raven/framework/Samplers/FactorialDesign.py", line 136, in localInitialize
framework.testFactorials:     if self.designMatrix != None:
framework.testFactorials: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
framework.testFactorials: 
```
and
```
framework/PostProcessors/BasicStatistics.grid_analytic: Exception in thread 0:
framework/PostProcessors/BasicStatistics.grid_analytic: Traceback (most recent call last):
framework/PostProcessors/BasicStatistics.grid_analytic:   File "/home/jjc/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
framework/PostProcessors/BasicStatistics.grid_analytic:     self.run()
framework/PostProcessors/BasicStatistics.grid_analytic:   File "/home/jjc/miniconda2/lib/python2.7/threading.py", line 754, in run
framework/PostProcessors/BasicStatistics.grid_analytic:     self.__target(*self.__args, **self.__kwargs)
framework/PostProcessors/BasicStatistics.grid_analytic:   File "/home/jjc/sub/raven/framework/Runners/SharedMemoryRunner.py", line 135, in <lambda>
framework/PostProcessors/BasicStatistics.grid_analytic:     self.thread = threading.Thread(target = lambda q, *arg : q.append(self.functionToRun(*arg)), name = self.identifier, args=(self.subque,)+tuple(self.args))
framework/PostProcessors/BasicStatistics.grid_analytic:   File "/home/jjc/sub/raven/framework/Models/PostProcessor.py", line 202, in evaluateSample
framework/PostProcessors/BasicStatistics.grid_analytic:     returnValue = (Input, self.interface.run(Input))
framework/PostProcessors/BasicStatistics.grid_analytic:   File "/home/jjc/sub/raven/framework/PostProcessors/BasicStatistics.py", line 1090, in run
framework/PostProcessors/BasicStatistics.grid_analytic:     outputDict = self.__runLocal(input)
framework/PostProcessors/BasicStatistics.grid_analytic:   File "/home/jjc/sub/raven/framework/PostProcessors/BasicStatistics.py", line 938, in __runLocal
framework/PostProcessors/BasicStatistics.grid_analytic:     if None in pbWeightsList:
framework/PostProcessors/BasicStatistics.grid_analytic: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or 
```

Libraries used:
* numpy 1.13.0 
* h5py 2.7.0 
* scipy 0.19.0 
* sklearn 0.18.1 
* matplotlib 2.0.2 

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
An email to the user group might be sent out of consideration, but isn't required.

**Comment by alfoa** [comment]
This should be closed
