### ISSUE TITLE
[DEFECT] SyntheticHistory ROM Interpolation Broken

### ISSUE THREAD

**Issue by dylanjm** [idaholab/raven#2389]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

I am trying to train a SyntheticHistory ROM using a 6 sets of data. I want the data sets 0-4 to represent years 2024-2028 and then I want to interpolate between 2029-2054 using the 5 set of data. 

When performing the training in RAVEN I get the following error:

```
Traceback (most recent call last):
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/bin/raven_framework", line 8, in <module>
    sys.exit(wheelMain())
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/Driver.py", line 34, in wheelMain
    main(False)
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/Driver.py", line 207, in main
    raven()
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/Driver.py", line 160, in raven
    simulation.run()
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/Simulation.py", line 901, in run
    self.executeStep(stepInputDict, stepInstance)
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/Simulation.py", line 834, in executeStep
    stepInstance.takeAstep(stepInputDict)
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/Steps/Step.py", line 317, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/Steps/RomTrainer.py", line 89, in _localTakeAstepRun
    ROM.train(inDictionary['Input'][0])
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/Models/ROM.py", line 372, in train
    self.supervisedContainer[0].train(self.trainingSet)
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/SupervisedLearning/ROMCollection.py", line 1644, in train
    self._interpolateSteps(tdict)
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/SupervisedLearning/ROMCollection.py", line 1706, in _interpolateSteps
    newModel = self._interpolateSVL(trainingDict, exampleRoms, exampleModel, self._macroTemplate, numSegments, globalInterp, interps, y)
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/SupervisedLearning/ROMCollection.py", line 1786, in _interpolateSVL
    params = exampleModel._roms[0].setGlobalRomFeatures(params, pivotValues)
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/SupervisedLearning/SyntheticHistory.py", line 370, in setGlobalRomFeatures
    params = algo.setClusteringValues(settings, self._tsaTrainedParams[algo])
  File "/Users/mcdodj/.local/share/pyenv/versions/3.10.0/lib/python3.10/site-packages/ravenframework/TSA/Fourier.py", line 316, in setClusteringValues
    params[target]['intercept'] = value
KeyError: 'TOTALLOAD'
```

### Steps to Reproduce

See attached files

### Expected Behavior

I expect the interpolation to happen without issue. 

### Screenshots and Input Files

[synthetic_history.zip](https://github.com/user-attachments/files/17509123/synthetic_history.zip)

### OS

MacOS

### OS Version

14.7

### Dependency Manager

PIP

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [ ] If the issue is a defect, is the defect fixed?
- [ ] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by j-bryan** [comment]
The issue appears to be in `SyntheticHistory.py`. When trying to set global ROM features, the loop
```for algo in self._tsaAlgorithms: ...``` (line 365)
should probably be looping over `self._tsaGlobalAlgorithms` instead.

**Comment by GabrielSoto-INL** [comment]
Working on fixing what Jacob just described. But I think the actual issue happens when there are multiple algorithm nodes with different targets (e.g., two `<fourier>` nodes, one for `target_0` and one for `target_1`). Seems I had implemented a fix but it's commented out on Line 368... unsure why that is, I will re-implemented in another branch with testing to cover that error.

**Comment by dylanjm** [comment]
Approved to close via #2394
