### ISSUE TITLE
Test CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe sometimes crashes on Linux

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#400]
--------
Issue Description
--------
##### What did you expect to see happen?
Tests should pass on all tested machines.

##### What did you see instead?
The test framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe sometimes crashes on Linux, the error messages are:
```
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: Working Directory: /home/moosetest/civet/client_root_0/raven/tests/framework/CodeInterfaceTests
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: Running command: python /home/moosetest/civet/client_root_0/raven/framework/Driver.py  interfaceCheck test_melcor_interface.xml
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: 
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: 
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:       .---.        .------######       #####     ###   ###  ########  ###    ###
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:      /     \  __  /    --###  ###    ###  ###   ###   ###  ###       #####  ###
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:     / /     \(  )/    --###  ###    ###   ###  ###   ###  ######    ### ######
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:    //////   ' \/ `   --#######     #########  ###   ###  ###       ###  #####
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:   //// / // :    :   -###   ###   ###   ###    ######   ####      ###   ####
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:  // /   /  /`    '---###    ###  ###   ###      ###    ########  ###    ###
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: //          //..\
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: ===========UU====UU=============================================================
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:            '//||\`
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:              ''``
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:     
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: 
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: Copyright 2017 Battelle Energy Alliance, LLC
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: 
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: Licensed under the Apache License, Version 2.0 (the "License");
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: you may not use this file except in compliance with the License.
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: You may obtain a copy of the License at
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: 
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: http://www.apache.org/licenses/LICENSE-2.0
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: 
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: Unless required by applicable law or agreed to in writing, software
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: distributed under the License is distributed on an "AS IS" BASIS,
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: See the License for the specific language governing permissions and
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: limitations under the License.
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:   
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) SIMULATION               : Message         -> Simulation started at 2017-10-06 11:35:26
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) SIMULATION               : Message         -> Global verbosity level is " debug "
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) SIMULATION               : DEBUG           -> -- Reading the block: RunInfo        --
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) SIMULATION               : DEBUG           -> -- Reading the block: Files          --
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) SIMULATION               : DEBUG           -> Reading type Input with name melcorinput
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) input File               : DEBUG           -> ------Reading Completed for:
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) input File               : DEBUG           ->        Type           : input
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) input File               : DEBUG           ->        Class          : UserGenerated   from <class 'Files.File'>
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) input File               : DEBUG           ->        Name           : melcorinput
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) input File               : DEBUG           ->        Initialization Parameters:
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.00 sec) input File               : DEBUG           ->        Current Setting:
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.01 sec) SIMULATION               : DEBUG           -> -- Reading the block: Models         --
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.01 sec) SIMULATION               : DEBUG           -> Reading type Code with name MELGEN
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.01 sec) Code                     : Message         -> not found executable MELCOR_2.2/bin/melcor ExceptedError
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: (    0.01 sec) Code                     : Message         -> not found preexec MELCOR_2.2/bin/melgen ExceptedError
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: Traceback (most recent call last):
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:   File "/home/moosetest/civet/client_root_0/raven/framework/Driver.py", line 222, in <module>
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:     simulation.XMLread(root,runInfoSkip=set(["DefaultInputFile"]),xmlFilename=inputFile)
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:   File "/home/moosetest/civet/client_root_0/raven/framework/Simulation.py", line 520, in XMLread
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:     self.whichDict[Class][name].readXML(childChild, self.messageHandler, varGroups, globalAttributes=globalAttributes)
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:   File "/home/moosetest/civet/client_root_0/raven/framework/BaseClasses.py", line 107, in readXML
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:     self._readMoreXML(xmlNode)
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:   File "/home/moosetest/civet/client_root_0/raven/framework/Models/Code.py", line 218, in _readMoreXML
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:     self.code = Code.CodeInterfaces.returnCodeInterface(self.subType,self)
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:   File "/home/moosetest/civet/client_root_0/raven/framework/CodeInterfaces.py", line 78, in returnCodeInterface
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:     return __interFaceDict[Type]()
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:   File "/home/moosetest/civet/client_root_0/raven/framework/CodeInterfaces/MELCOR/melcorCombinedInterface.py", line 40, in __init__
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:     self.melcorInterface = MelcorApp()
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:   File "/home/moosetest/civet/client_root_0/raven/framework/CodeInterfaces/MELCOR/melcorInterface.py", line 39, in __init__
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe:     MelgenApp.__init__(self)
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: TypeError: unbound method __init__() must be called with MelgenApp instance as first argument (got MelcorApp instance instead)
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: 
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: ################################################################################
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: Tester failed, reason: CWD /home/moosetest/civet/client_root_0/raven METHOD opt Expected files not created /home/moosetest/civet/client_root_0/raven/tests/framework/CodeInterfaceTests/MelcorInterface/dumpMelcorHistorySet_2.csv /home/moosetest/civet/client_root_0/raven/tests/framework/CodeInterfaceTests/MelcorInterface/dumpMelcorHistorySet.csv
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe: 
framework/CodeInterfaceTests.melcorInterfaceForwardSamplingNoExe FAILED (CWD /home/moosetest/civet/client_root_0/raven METHOD opt Expected files not created /home/moosetest/civet/client_root_0/raven/tests/framework/CodeInterfaceTests/MelcorInterface/dumpMelcorHistorySet_2.csv /home/moosetest/civet/client_root_0/raven/tests/framework/CodeInterfaceTests/MelcorInterface/dumpMelcorHistorySet.csv)
```

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? __No impact__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __Code crashes__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

Reviewed by Congjian Wang @wangcj05 on Oct. 6, 2017.
-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@joshua-cogliati-inl FYI, I created this issue for the failed ```melcorInterfaceForwardSamplingNoExe``` test.

**Comment by alfoa** [comment]
It has been fixed. (pr #353)

Closing...
