### ISSUE TITLE
[rework] Optimizer and point-probability

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#606]
In RAVEN running RAVEN, when the outer RAVEN reads a data obj from inner RAVEN that was created by a Optimizer, the point-probability fails as follows:

```
WARNING: XML node "PointSet" != param spec name "DataSet"
<DataObjects.XDataObject.MessageCourier instance at 0x1148d7950> <DataObjects.XPointSet.PointSet object at 0x1148a4610> Reading data from "/Users/epinas/projects/hybrid/CashFlowCalcs/2017September_INLEXT-17-42441/Opt_C_NoModelica_D_TEST/./OPTrun/RrR++0_0_0/./Back_to_MASTER.csv.csv" DEBUG debug None
<DataObjects.XDataObject.MessageCourier instance at 0x1148d7950> <DataObjects.XPointSet.PointSet object at 0x1148a4610> Reading metadata from "/Users/epinas/projects/hybrid/CashFlowCalcs/2017September_INLEXT-17-42441/Opt_C_NoModelica_D_TEST/./OPTrun/RrR++0_0_0/./Back_to_MASTER.xml" DEBUG debug None
Exception in thread RrR++0_0_0:
Traceback (most recent call last):
  File "/Users/epinas/.conda/envs/raven_libraries/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/epinas/.conda/envs/raven_libraries/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/epinas/projects/raven/framework/Runners/SharedMemoryRunner.py", line 135, in <lambda>
    self.thread = threading.Thread(target = lambda q, *arg : q.append(self.functionToRun(*arg)), name = self.identifier, args=(self.subque,)+tuple(self.args))
  File "/Users/epinas/projects/raven/framework/Models/Code.py", line 573, in evaluateSample
    rlz['PointProbability'] = np.atleast_1d(rlz.get('PointProbability',1.0) * kwargs.get('PointProbability',1.0))
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```

**Comment by PaulTalbot-INL** [comment]
This should have been closed automatically by #610.  I'm not sure why it didn't.
