### ISSUE TITLE
DMD ROM not well pickled 

### ISSUE THREAD

**Issue by PassengerC07** [idaholab/raven#673]
--------
Issue Description
--------
##### What did you expect to see happen?

The pickled DMD ROM to function well on propagating data over a uniform grid.

##### What did you see instead?

Error messages regarding failed jobs:

Traceback (most recent call last):
  File "/apps/local/easybuild/software/Python/2.7.9-gmvolf-5.5.4/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/apps/local/easybuild/software/Python/2.7.9-gmvolf-5.5.4/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/chenj/RAVEN/projects/raven/framework/Runners/SharedMemoryRunner.py", line 135, in <lambda>
    self.thread = threading.Thread(target = lambda q, *arg : q.append(self.functionToRun(*arg)), name = self.identifier, args=(self.subque,)+tuple(self.args))
  File "/home/chenj/RAVEN/projects/raven/framework/Models/ROM.py", line 427, in evaluateSample
    result = self._externalRun(inRun)
  File "/home/chenj/RAVEN/projects/raven/framework/Models/ROM.py", line 406, in _externalRun
    returnDict = self.evaluate(inRun)
  File "/home/chenj/RAVEN/projects/raven/framework/Models/ROM.py", line 394, in evaluate
    outputEvaluation = self.supervisedEngine.evaluate(inputToROM)
  File "/home/chenj/RAVEN/projects/raven/framework/LearningGate.py", line 200, in evaluate
    sliceEvaluation = rom.evaluate(request)
  File "/home/chenj/RAVEN/projects/raven/framework/SupervisedLearning.py", line 272, in evaluate
    return self.__evaluateLocal__(featureValues)
  File "/home/chenj/RAVEN/projects/raven/framework/SupervisedLearning.py", line 3325, in __evaluateLocal__
    weights, indexes = self.KDTreeFinder.query(featureVals, k=min(2**len(self.features),len(reconstructData)))
  File "/apps/local/easybuild/software/Python/2.7.9-gmvolf-5.5.4/lib/python2.7/site-packages/scipy/spatial/kdtree.py", line 497, in query
    hits = self.__query(x[c], k=k, eps=eps, p=p, distance_upper_bound=distance_upper_bound)
  File "/apps/local/easybuild/software/Python/2.7.9-gmvolf-5.5.4/lib/python2.7/site-packages/scipy/spatial/kdtree.py", line 365, in __query
    if x[node.split_dim] < node.split:
AttributeError: 'leafnode' object has no attribute 'split_dim'

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[L&S_DMD.xml.zip](https://github.com/idaholab/raven/files/2069709/L.S_DMD.xml.zip)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
An email should be sent to the users, and I think this defect will not impact the latest stable branch.

**Comment by wangcj05** [comment]
Checklist is satisfied, and an email is proposed in PR#673
