### ISSUE TITLE
If illegal XML named variables are present, the code crashes

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#733]
--------
Issue Description
--------
##### What did you expect to see happen?
Ability to load CSV files with invalid XML variables (e.g. containing "/", etc)

##### What did you see instead?
If a variable has an invalid XML character (e.g. "/", "$", etc.), the XML utilis methods (used to write out the metadata) is going to replace it with a "."  when constructing the XML metadata (node <dim>).
Since the new variables do not match any of the output variables, those variables are not written in the auxiliary metadata XML file. This causes the code to crash when trying to reload the CSVs. When the variables are read back, the code does not find the Index of the "illegal" variables (not written in the XML) defined in the <Output> block. 

For example, When we dump the following variables we get this warning:
```
XML UTILS: Replacing illegal tag characters in "u-234_atoms/barn-cm": u-234_atoms.barn-cm
XML UTILS: Replacing illegal tag characters in "ag-107_atoms/barn-cm": ag-107_atoms.barn-cm
XML UTILS: Replacing illegal tag characters in "u-235_atoms/barn-cm": u-235_atoms.barn-cm
```
When they are read back, the illegal named variables (e.g. ag-107_atoms/barn-cm) are not found in the XML  and consequentially are not stored in the dict ```self._pivotParams```. This leaves variables in the output space without any index linked to them and consequentially, when the method ```asDataset``` gets called, an unexpected crash happens:

```
(   43.79 sec) HistorySet               : DEBUG           -> Reading data from "/Users/alfoa/projects/raven_github/raven/dh_chenj/samples/originalModelCSV/history_time_evolution_2017.csv.csv"
(   43.81 sec) HistorySet               : DEBUG           -> Reading data from "/Users/alfoa/projects/raven_github/raven/dh_chenj/samples/originalModelCSV/history_time_evolution_2018.csv.csv"
(   43.83 sec) HistorySet               : DEBUG           -> Reading data from "/Users/alfoa/projects/raven_github/raven/dh_chenj/samples/originalModelCSV/history_time_evolution_2019.csv.csv"
Traceback (most recent call last):
  File "/Users/alfoa/projects/raven_github/raven/framework/Driver.py", line 281, in <module>
    raven()
  File "/Users/alfoa/projects/raven_github/raven/framework/Driver.py", line 234, in raven
    simulation.run()
  File "/Users/alfoa/projects/raven_github/raven/framework/Simulation.py", line 798, in run
    stepInstance.takeAstep(stepInputDict)
  File "/Users/alfoa/projects/raven_github/raven/framework/Steps.py", line 312, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/Users/alfoa/projects/raven_github/raven/framework/Steps.py", line 947, in _localTakeAstepRun
    outputs[i].load(inDictionary['Input'][i].getPath(),'csv',**options)
  File "/Users/alfoa/projects/raven_github/raven/framework/DataObjects/DataSet.py", line 433, in load
    self._fromCSV(fileName,**kwargs)
  File "/Users/alfoa/projects/raven_github/raven/framework/DataObjects/HistorySet.py", line 154, in _fromCSV
    self.load(data,style='dict',dims=self.getDimensions())
  File "/Users/alfoa/projects/raven_github/raven/framework/DataObjects/DataSet.py", line 435, in load
    self._fromDict(fileName,**kwargs)
  File "/Users/alfoa/projects/raven_github/raven/framework/DataObjects/DataSet.py", line 1257, in _fromDict
    self.asDataset()
  File "/Users/alfoa/projects/raven_github/raven/framework/DataObjects/DataSet.py", line 260, in asDataset
    return self._convertToXrDataset()
  File "/Users/alfoa/projects/raven_github/raven/framework/DataObjects/DataSet.py", line 1079, in _convertToXrDataset
    arrays[var][self.sampleTag] += firstSample
KeyError: u'u-234_atoms/barn-cm'

```

##### Do you have a suggested fix for the development team?
Either 
the illegal XML character should be replaced with a "token" recognizable in the loading stage => we will able to identify it and connect them back with the original variables 
or 
we move from : 
```
    <dims>
      <totals_watts>time</totals_watts>
    </dims>
```
to 
```
    <dims>
      <var name="totals_watts">time</var>
      <var name="ag-107_atoms/barn-cm">time</var>
    </dims>
```
or 
change the DataObject.py method ```setPivotParameter``` to:
```
  def setPivotParams(self,params):
    """
      Sets the pivot parameters for variables.
      @ In, params, dict, var:[params] as str:list(str)
      @ Out, None
    """
    # TODO typechecking, assertions
    coords = set().union(*params.values())
    for coord in coords:
      if coord not in self._pivotParams:
        self._pivotParams[coord] = list(var for var in params.keys() if coord in params[var])
      else:
        self._pivotParams[coord] = list(set(list(var for var in params.keys() if coord in params[var]) + self._pivotParams[coord]))
```
##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@PaulTalbot-INL I assigned this to you but I will fix this in case it is not done within Monday morning.

**Comment by alfoa** [comment]
It has been addressed.
