### ISSUE TITLE
HistorySetSampling does not handle the HistorySet correctly

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#739]
--------
Issue Description
--------
##### What did you expect to see happen?
For given HistorySet, the code should run successfully. 

##### What did you see instead?
```
The code crashed:
Traceback (most recent call last):
  File "/Users/wangc/projects/wangc/raven/framework/Driver.py", line 281, in <module>
    raven()
  File "/Users/wangc/projects/wangc/raven/framework/Driver.py", line 234, in raven
    simulation.run()
  File "/Users/wangc/projects/wangc/raven/framework/Simulation.py", line 798, in run
    stepInstance.takeAstep(stepInputDict)
  File "/Users/wangc/projects/wangc/raven/framework/Steps.py", line 312, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/Users/wangc/projects/wangc/raven/framework/Steps.py", line 466, in _localTakeAstepRun
    model.collectOutput(finishedJob,output)
  File "/Users/wangc/projects/wangc/raven/framework/Models/PostProcessor.py", line 240, in collectOutput
    self.interface.collectOutput(finishedjob,output)
  File "/Users/wangc/projects/wangc/raven/framework/PostProcessors/InterfacedPostProcessor.py", line 198, in collectOutput
    output.load(evaluation['data'], style='dict', dims=evaluation['dims'])
  File "/Users/wangc/projects/wangc/raven/framework/DataObjects/DataSet.py", line 435, in load
    self._fromDict(fileName,**kwargs)
  File "/Users/wangc/projects/wangc/raven/framework/DataObjects/DataSet.py", line 1257, in _fromDict
    self.asDataset()
  File "/Users/wangc/projects/wangc/raven/framework/DataObjects/DataSet.py", line 260, in asDataset
    return self._convertToXrDataset()
  File "/Users/wangc/projects/wangc/raven/framework/DataObjects/DataSet.py", line 1074, in _convertToXrDataset
    raise e
ValueError: setting an array element with a sequence.
```
##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
The issue does not cause bad results but a crash of the code... No email needed.

Closure checklist passed...
