### ISSUE TITLE
The reset of NDSpline rom crashed

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#771]
--------
Issue Description
--------
##### What did you expect to see happen?
NDSpline can be reseted 

##### What did you see instead?
```
Traceback (most recent call last):
  File "/Users/wangc/projects/wangc/raven/framework/Driver.py", line 281, in <module>
    raven()
  File "/Users/wangc/projects/wangc/raven/framework/Driver.py", line 234, in raven
    simulation.run()
  File "/Users/wangc/projects/wangc/raven/framework/Simulation.py", line 798, in run
    stepInstance.takeAstep(stepInputDict)
  File "/Users/wangc/projects/wangc/raven/framework/Steps.py", line 312, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/Users/wangc/projects/wangc/raven/framework/Steps.py", line 680, in _localTakeAstepRun
    model.submit(newInput, inDictionary[self.samplerType].type, jobHandler, **copy.deepcopy(sampler.inputInfo))
  File "/Users/wangc/projects/wangc/raven/framework/Models/HybridModel.py", line 579, in submit
    self.trainRom(samplerType, kwargs)
  File "/Users/wangc/projects/wangc/raven/framework/Models/HybridModel.py", line 332, in trainRom
    romInfo['Instance'].reset()
  File "/Users/wangc/projects/wangc/raven/framework/Models/ROM.py", line 346, in reset
    self.supervisedEngine.reset()
  File "/Users/wangc/projects/wangc/raven/framework/LearningGate.py", line 112, in reset
    rom.reset()
(   76.60 sec) HybridModel              : DEBUG           -> Evaluate Sample
  File "/Users/wangc/projects/wangc/raven/framework/SupervisedLearning/SupervisedLearning.py", line 247, in reset
(   76.60 sec) HybridModel              : DEBUG           -> Create New Input
    (   76.60 sec) HybridModel              : DEBUG           -> External Run
self.__resetLocal__()
  File "/Users/wangc/projects/wangc/raven/framework/SupervisedLearning/NDsplineRom.py", line 107, in __resetLocal__
    self.interpolator[index].reset()
(   76.61 sec) Code                     : Message         -> job "mammoth++16" submitted!
  File "/Users/wangc/projects/wangc/raven/crow/install/crow_modules/interpolationNDpy2.py", line 230, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, NDSpline, name)
(   76.61 sec) HybridModel              : DEBUG           -> Job submitted for model  mammoth  with identifier  16
  File "/Users/wangc/projects/wangc/raven/crow/install/crow_modules/interpolationNDpy2.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'NDSpline' object has no attribute 'reset'
```

##### Do you have a suggested fix for the development team?

Fix the __resetLocal__ in the NDsplineRom.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Not valid anymore, the following methods are used to reset the rom:
![image](https://user-images.githubusercontent.com/7321071/177876455-f3f9fcbb-f385-4e25-bb3c-2d492a119b2c.png)
