### ISSUE TITLE
LimitSurface Postprocessor Crashed with unrecognized variables 

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#772]
--------
Issue Description
--------
In Samplers we allow the users to input multiple variables associate to one xml ```<variable name='x1,x2,...'>```  node, however, in some PostProcessor, we did not handle this correctly. For example, in LimitSurface Postprocessor, we just directly pass the whole string ```x1,x2,...``` to the Functions, which causes the code crashed. 

##### What did you expect to see happen?
LimitSurface Postprocessor should work

##### What did you see instead?

```
Traceback (most recent call last):
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Driver.py", line 281, in <module>
    raven()
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Driver.py", line 234, in raven
    simulation.run()
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Simulation.py", line 798, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Steps.py", line 309, in takeAstep
    self._initializeStep(inDictionary)
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Steps.py", line 244, in _initializeStep
    self._localInitializeStep(inDictionary)
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Steps.py", line 601, in _localInitializeStep
    if inDictionary[self.samplerType].amIreadyToProvideAnInput():
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Samplers/Sampler.py", line 629, in amIreadyToProvideAnInput
    ready = self.localStillReady(ready)
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Samplers/LimitSurfaceSearch.py", line 430, in localStillReady
    self.limitSurfacePP._initializeLSppROM(self.lastOutput,False)
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/PostProcessors/LimitSurface.py", line 191, in _initializeLSppROM
    indexEnd = len(self.functionValue[self.axisName[0]]) - 1
KeyError: u'1|11070501:5,1|11070601:5,1|11080501:5,1|11080601:5,1|11090501:5,1|11090601:5'
```

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
       No wrong results, but the code crashed. 
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
As discussed today, a more general approach should be implemented to handle the correlated parameters instead of using comma separated strings.
