### ISSUE TITLE
InterfacePostProcessor HS2PS crashed.

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#799]
--------
Issue Description
--------
##### What did you expect to see happen?
InterfacePostProcessor should run

##### What did you see instead?
```
/Users/wangc/projects/raven/framework/DataObjects/DataSet.py:614: FutureWarning: calling len() on an xarray.Dataset will change in xarray v0.11 to only include data variables, not coordinates. Call len() on the Dataset.variables property instead, like ``len(ds.variables)``, to preserve existing behavior in a forwards compatible manner.
  if self._data is None or len(self._data) == 0:
Exception in thread 0:
Traceback (most recent call last):
  File "/Users/wangc/miniconda2/envs/raven_libraries/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/wangc/miniconda2/envs/raven_libraries/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/wangc/projects/raven/framework/Runners/SharedMemoryRunner.py", line 135, in <lambda>
    self.thread = threading.Thread(target = lambda q, *arg : q.append(self.functionToRun(*arg)), name = self.identifier, args=(self.subque,)+tuple(self.args))
  File "/Users/wangc/projects/raven/framework/Models/PostProcessor.py", line 229, in evaluateSample
    returnValue = (Input, self.interface.run(Input))
  File "/Users/wangc/projects/raven/framework/PostProcessors/DataMining.py", line 550, in run
    Input = self.inputToInternal(inputIn)
  File "/Users/wangc/projects/raven/framework/PostProcessors/DataMining.py", line 364, in inputToInternal
    return self.inputToInternalForHistorySet(currentInput)
  File "/Users/wangc/projects/raven/framework/PostProcessors/DataMining.py", line 259, in inputToInternalForHistorySet
    return self.inputToInternalForPreProcessor(currentInput)
  File "/Users/wangc/projects/raven/framework/PostProcessors/DataMining.py", line 330, in inputToInternalForPreProcessor
    preProcessedData = self.PreProcessor.interface.run(tempData)
  File "/Users/wangc/projects/raven/framework/PostProcessors/InterfacedPostProcessor.py", line 136, in run
    inputTypes = set([inp.type for inp in inputIn])
AttributeError: 'dict' object has no attribute 'type'
```
##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.
Test: doc/workshop/timeDepDataMining/inputs/TD_KMeans.xml

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
checklist is good, and issue can be closed with PR#1886
